### ISSUE TITLE
Summary - Salt: Combining ACID and BASE in a Distributed Database

### ISSUE THREAD

**Issue by reddheeraj** [tapaswenipathak/linux-kernel-stats#100]
https://www.usenix.org/system/files/conference/osdi14/osdi14-paper-xie.pdf

**Comment by reddheeraj** [comment]
**Salt: Combining ACID and BASE in a Distributed Database**

**ABSTRACT**
The paper introduces **Salt**, a distributed database that aims to improve the performance and scalability of ACID applications by adopting the BASE approach. It is based on the Pareto principle that only a few transactions in an application push the limits of ACID performance. Salt introduces BASE transactions that retain atomicity and durability but offer different levels of isolation depending on whether they are BASE or ACID transactions. This allows for the performance benefits of the BASE paradigm without compromising the guarantees of ACID. 

**INTRODUCTION**
**Salt** is a distributed database that allows for the combination of the **ACID** (Atomicity, Consistency, Isolation, Durability) and **BASE** (BasicallyAvailable, Soft state, Eventually consistent) paradigms in a single application. The ACID paradigm provides an easy-to-use programming abstraction but with a cost to performance and availability. On the other hand, BASE offers performance gains but requires developers to manually code consistency logic. 

Transactions in BASE systems relax the strict association between atomicity and isolation that is required by the ACID model, providing a special blend of features: it combines the performance improvement and availability benefits of partition-local transactions in the BASE style with the capability to define and enforce atomicity at the level required by the application's meaning.
The authors propose a new concept called **Salt Isolation**, which combines the best features of both ACID and BASE transactions. Salt Isolation allows BASE transactions to observe each other's internal states for **improved performance** while ensuring that **ACID transactions remain isolated**. The authors built a prototype based on the MySQL Cluster database and showed that combining ACID and BASE paradigms can result in high performance with modest programming effort. 
The authors describe the **dilemma faced by database application developers** as their application becomes popular and the performance of the original ACID implementation becomes inadequate. The ACID/BASE choice highlights the tradeoff between performance and robustness, with BASE giving up atomicity, consistency, and durability, and offering only limited isolation.

The **Pareto principle** suggests that not all transactions require high performance, leading to the possibility of only BASE-ifying performance-critical transactions for performance benefits. However, BASE-ifying even a few transactions can cause problems with accessibility to intermediate states, which is protected in ACID transactions through isolation and atomicity. T
The ACID transactions are both powerful and easy to program with due to the tight coupling of atomicity and isolation, but this limits their ability to deliver ease of programming when performance demands increase. **Splitting the ACID transaction into smaller transactions** can improve performance but **reduces the original transaction's guarantees** in terms of atomicity and isolation, leading to indiscriminate access to intermediate states by other transactions, making it harder to reason about the correctness of the application.
So, the authors propose **loosening the coupling between atomicity and isolation** with the introduction of BASE transactions, which borrow from nested transactions to provide isolation at a finer granularity without sacrificing atomicity. This allows for greater control over access to intermediate states, i**mproving performance without sacrificing ease of programming**.

**Base Transactions**
A BASE transaction is delimited by "begin BASE transaction" and "end BASE transaction" statements and consists of a sequence of alkaline sub-transactions. BASE transactions provide the same atomicity as traditional nested transactions and offer "Salt Isolation", a new isolation property that allows for multiple levels of isolation. Alkaline sub-transactions retain the properties of ACID transactions and can be partition-local or distributed. BASE transactions are accepted as soon as the first alkaline sub-transaction commits and have two important events in their life cycle: accept and commit. Once accepted, a BASE transaction will eventually commit and its results will be recorded.

BASE transactions provide Atomicity, Consistency, Isolation, and Durability (ACID) guarantees, similar to ACID transactions, but with some differences. **Atomicity** ensures all operations in a transaction occur or none do, and committed BASE transactions are eventually executed. **Consistency** is achieved by reducing the number of interleavings to enforce integrity constraints, through selective enforcement and limiting visibility of states. **Isolation** offers a new property called Salt Isolation, which allows for higher performance and respects the isolation property offered by ACID transactions. **Durability** of BASE transactions is the same as ACID transactions, ensuring accepted transactions are durable and won't be lost.

**Salt Isolation**
The goal of Salt isolation is to allow **high levels of concurrency for BASE** transactions while ensuring isolation guarantees for ACID transactions. The design focuses on lock-based implementations for simplicity and high contention, but other mechanisms can be used in the future. The isolation guarantees for ACID transactions are defined by a simple requirement that if two operations in different transactions conflict, the **temporal dependency** between them must extend to the entire transaction. This formulation can express all four ANSI/ISO SQL isolation levels. The challenge is defining an isolation property for BASE transactions that allows them to coexist with ACID transactions without harming the isolation guarantees. The key to Salt isolation is controlling which transactions are exposed to others.
Salt isolation is a method used to enforce the isolation property in ACID transactions. The isolation property is enforced in Salt Isolation by using locks, each transaction type has its own lock: **ACID locks, Alkaline locks and Saline locks**. **ACID locks** are used in traditional ACID systems and are held either short-term or long-term depending on the operation type. **Alkaline locks** keep alkaline sub-transactions isolated from ACID and alkaline sub-transactions and can also be short-term or long-term. **Saline locks** are used to isolate ACID transactions from BASE transactions, and increase concurrency by exposing intermediate states of BASE transactions to other BASE transactions. If Salt Isolation is enforced naively, indirect instances of undesirable phenomena may occur, such as indirect dirty reads. In these cases, the Isolation property may not be enforced between pairs of BASE transactions, leading to violations of transaction isolation guarantees.

**Implementation**
In this study, the researchers modified the popular distributed database MySQL Cluster to support BASE transactions and enforce Salt Isolation. The database is divided into partitions and each partition follows a master-slave protocol to maintain consistency. The locking module of MySQL Cluster was modified to support alkaline and saline locks, which includes handling lock conflicts, controlling when each type of lock should be acquired and released, and a queuing mechanism to enforce the order in which locks are released. The current prototype uses the read-committed isolation level.

To improve availability and reduce latency, Salt supports early commit for BASE transactions, where a client is notified that the transaction has been committed as soon as its first subtransaction commits. The transaction logic is logged before the first subtransaction commits to ensure atomicity and durability even in case of failures.

In case of failures, the system has a two-phase recovery protocol: redo and roll forward. In the redo phase, the redo log is replayed to ensure that all operations are executed eventually. The roll forward phase uses the logged transaction logic to regenerate the transaction's query plan and reissue the operations. The system also tracks direct dependencies among transactions to avoid indirect dirty reads.

To enhance performance, Salt has a local-transaction optimization that leverages the fact that alkaline subtransactions tend to be small, often containing only one operation. When an alkaline subtransaction consists of a single operation, the partition replicas can locally commit the transaction and release the corresponding locks immediately after the operation is completed.

**Experiments and results**

**Performance Comparison between Salt and ACID:**
In the TPC-C benchmark, the ACID implementation achieved a peak throughput of 1464 transactions/sec, while the Salt implementation, by BASE-ifying only two transactions (new-order and payment), achieved a throughput of 9721 transactions/sec, 6.6x higher than ACID.
In the Fusion Ticket benchmark, the ACID implementation achieved a throughput of 1088 transactions/sec, while Salt, by BASE-ifying only one transaction (create-order), achieved a throughput of 7090 transactions/sec, 6.5x higher than ACID.

**Programming Effort vs. Throughput:**
In the TPC-C benchmark, even with only two BASE-ified transactions, Salt achieved 80% of the maximum throughput of a pure BASE implementation.
In the Fusion Ticket benchmark, BASE-ifying one transaction took about 15 man-hours and changing 55 lines of code out of a total of 180,000. BASE-ifying this first transaction yields a benefit of 6.5x over ACID, while BASE-ifying additional transactions did not produce significant additional performance benefits.

**Contention Management:**
The authors found that by BASE-ifying only the most contented transactions, Salt was able to significantly reduce lock wait time, increasing concurrency and boosting performance.
Overall, the experiments showed that BASE-ifying only a few transactions, particularly the most contented ones, can yield significant performance gains compared to traditional ACID implementations.

**Related Work**
The traditional database system relies on ACID's strong guarantees to simplify application development, but it has performance limitations. Several approaches have been proposed to improve the performance of distributed ACID transactions, but they have limitations. Many recent systems have adopted the BASE approach to achieve higher performance and availability by offering limited transactions that only access a single item. To mitigate complexity, several solutions have been proposed to provide stronger semantics but with limited atomicity or isolation across partitions.

To conclude, **Salt offers a solution to the ACID/BASE dualism** by providing a way to have the best of both worlds. Salt allows developers to balance ease of programming and performance. The effort required to increase performance is modest and can result in significant benefits, making it a drama-free path for companies to grow their transactional applications.

**Comment by KavitaMeena23** [comment]
**Reviewed**

**Comment by duttabhishek0** [comment]
@tapaswenipathak
