### ISSUE TITLE
verification of output_diffstat_mainVersions.txt

### ISSUE THREAD

**Issue by PankajGoswami11** [tapaswenipathak/linux-kernel-stats#110]

**Comment by PankajGoswami11** [comment]
### Verification of output_diffstat_allVersions.txt

0.01..v0.10   80 files changed		                          _verified_  
v0.10..v0.11   49 files changed	                          _verified_
		**Rc. version**
v2.6.18-rc1..v2.6.18-rc2  1097 files changed         _found 1 file change_ 
```

**Comment by duttabhishek0** [comment]
@tapaswenipathak closing as verification complete.
