### ISSUE TITLE
Summary: DJoin - Differentially Private Join Queries over Distributed Databases

### ISSUE THREAD

**Issue by KavitaMeena23** [tapaswenipathak/linux-kernel-stats#111]
https://www.usenix.org/system/files/conference/osdi12/osdi12-final-164.pdf

**Comment by KavitaMeena23** [comment]
**Problem Statement:**
The problem of answering queries about private data that is spread across multiple different databases is studied. The separation of data prevents the processing of such queries,even if the final answer, e.g., a correlation coefficient,
would be safe to release.This is the problem of secure multi-party computation (MPC). The goal of MPC is to allow multiple parties to jointly compute a function on their private inputs without revealing their inputs to each other. The MPC protocols allow the parties to securely compute functions such as correlations, sums, or averages while preserving the privacy of their inputs. The MPC solutions can be used to answer queries about private data in a privacy-preserving manner, by allowing the parties holding the data to collaborate in the computation without exposing their data. 

**Proposed Solution:**
To overcome the above mentioned problem, DJoin has been developed. It is a privacy-preserving system for answering queries about private data that is spread across multiple databases. It uses two novel primitives, BN-PSI-CA and DCR, to support SQL-style queries, including joins. The system provides strong differential privacy guarantees on the results of the queries. The experimental evaluation of DJoin shows that it can process realistic queries in practical timescales, with simple queries on three databases taking between 1 and 7.5 hours.
Differential privacy is a privacy-preserving technique used to protect sensitive information while still allowing the analysis of large data sets. It aims to ensure that the results of a query or analysis on a dataset do not reveal any sensitive information about an individual. The method involves adding noise to the data and restricting the types of queries that can be made to the data, which helps to protect the privacy of individuals in the dataset. There are several differentially private query processors available, including PINQ, Airavat, Fuzz, and PDDP, which offer different features and capabilities to perform private data analysis.
However, the existing query processors mentioned in the text are not suitable for handling multiple databases simultaneously as they assume either that the data is in a single database or that subqueries can be answered using only one database.
DJoin is a novel system that allows for secure join processing across multiple databases without requiring the data to be in a single database or breaking the queries into subqueries. Instead, DJoin leverages secure multi-party computation and differential privacy to process joins in a more efficient manner, making it practical for larger computational tasks. The cost of processing joins with DJoin is expected to be lower compared to using MPC for the entire join.
Blinded, noised private set intersection cardinality (BN-PSI-CA) and denoise-combine-renoise (DCR) are two techniques developed to support private set intersection cardinality, which allows for efficient and secure computation of set intersection sizes. BN-PSI-CA extends the set-intersection protocol by adding private noising to it, while DCR is an operator that can add or subtract multiple noised subset cardinalities. The complexity of DCR grows with the number of parties involved in the computation, but not with the number of elements in the sets, making it efficient for large datasets. The authors of the paper report that the DCR step in their queries never took more than 20 seconds, indicating its practicality for real-world applications.
The results of the study indicate that the costs associated with the techniques presented (BN-PSI-CA and DCR) are substantial but still feasible for practical use.
DJoin is a cost-effective solution for research studies that can handle some latency, as its algorithms are easily parallelizable, allowing for speed improvement with more cores.

**Related Work:**
DJoin offers strong privacy protection through differential privacy, compared to weaker alternatives like randomization, k-anonymity, and l-diversity which can be vulnerable to privacy attacks.
Differentially private query processors: PINQ, Airavat, and Fuzz are query processors that support differential privacy. They are designed for a centralized setting, where the entire data is accessible by a single entity, which is responsible for processing queries and returning results.
DJoin supports query processing through joins, which allows for the combination and analysis of data from different databases. This makes DJoin's data model more general and adaptable to a wider range of use cases.

**Private set operations:**
The first protocols for private two-party set intersection and set intersection cardinality were proposed by Freedman et al. in [14]. There have been many improvements proposed since then, making the protocols more efficient and secure. The protocols mentioned produce exact results and are not designed for differential privacy, which introduces random noise to the data to maintain privacy.

**Computational differential privacy:**
DJoin provides computational differential privacy, relying on homomorphic cryptosystems and computational hardness assumptions. Mironov et al. demonstrated a protocol for approximating the Hamming distance between two vectors in a two-party setting, which is closely related to computing the cardinality of set intersections, which is solved by BN-PSI-CA.

**Untrusted servers:**
In SUNDR, SPORC, and Depot, the server provides storage, while in CryptDB, it implements a database and SQL-style queries. This approach is complementary to the goal of DJoin, which aims to reveal useful information about stored data while limiting the amount of information that can be learned about a single individual, through the use of differential privacy.

**Background:**
Differential privacy is a property of randomized queries that take a database as input and return aggregate results, such as a count or histogram. The database is viewed as a collection of rows, each row representing the data from a single individual, and the aim of differential privacy is to protect the privacy of individual records in the database by adding random noise to the results.
Practical solutions for achieving differential privacy rely on adding noise to the result. The amount of noise required depends on the sensitivity of the query, which refers to how much the result can change in response to changing the data in a single row. The noise added should be sufficient to ensure that the privacy of individual records in the database is protected.

**Challenge: Distribution**
Distributed queries can often be factored into several subqueries that can each be executed on an individual database, allowing for more efficient and privacy-preserving query processing. This way, individual databases do not need to reveal all of their data to other parties, reducing the risk of privacy breaches.
Some existing systems support this type of distributed query processing by factoring a query into several subqueries that can be executed on individual databases However, not all queries can be factored in this way and alternative solutions may be needed for these types of queries.
Some complex queries, such as joins, cannot be expressed as a series of subqueries and require alternative solutions such as general-purpose multi-party computation (MPC). However, the runtimes for state-of-the-art MPC solutions can be huge and may not be practical for some use cases.

**Approach:**
The key insight behind the solution is that joins are rarely used to compute full cross products of different databases, but instead they are often used to match elements from different databases. This observation is useful in finding more efficient and privacy-preserving solutions for joint operations.

**PSI-CA (Private Set-Intersection Cardinality)** is a primitive used in differential privacy solutions. It allows a group of k curators with multisets S1, S2, ..., Sk to privately compute |iSi|, i.e., the number of elements they have in common, but not the specific elements. PSI-CA has been well-studied in the past but not in the context of differential privacy. One simple PSI-CA primitive for two curators in the honest-but-curious (HbC) model uses homomorphic encryption, such as Paillier's cryptosystem, that preserves addition and allows multiplication by a constant.

The basic PSI-CA primitive is not compatible with differential privacy because it does not protect the privacy of individual data items and can result in the exact size of the intersection being known. To overcome this, the primitive can be extended to ensure differential privacy.
Secure multi-party computation (MPC) is a method to compute a function using private inputs from multiple players without revealing the inputs to each other. MPC is not practical for complex functions or large inputs but can process simple functions quickly in modern implementations. MPC can be used to combine a small number of subquery results.

**DCR: Cooperative noising**
MPC allows for the removal of noise added to individual cardinalities by BN-PSI-CA. However, sufficient noise N must be added back through MPC to prevent information leakage. This new noise must be unpredictable and not controlled by any individual curator.

**Query language: SPJU**
The approach uses a simple query language called SPJU (Selection, Projection, Cross join, and Union), which consists of SQL-style operators for these operations. It is a simpler language than SQL but can capture many important distributed operations.
Each query in SPJU can be translated into relational algebra using combinations of selections (σ), projections (π), joins (⨝), unions (∪), and counts (|·|).

**Three-tier query plan**
The approach has a three-tier structure:

- The first tier (sigmaex and setex) consists of local selections and projections that only involve one database; can be evaluated using classical database operations on individual databases.
- The second tier (cardex) consists of set intersection cardinalities; can be evaluated using BN-PSI-CA
- The third tier (query) consists of arithmetic operations on cardinalities; can be evaluated using DCR.


**Limitations:**
DJoin only supports two distributed operators: BN-PSI-CA and DCR. If a query cannot be translated into a query plan using only these operators and some purely local ones, it cannot be executed using DJoin.
DJoin supports predicates that:
- Use only fields from a single database.
- Perform equality tests between fields from different databases.
- Are conjunctions or disjunctions of these predicates.
- DJoin also supports inequalities and numeric comparisons using explicit rewrite rules. 
- DJoin is currently limited to counting queries and does not support sum queries or queries with non-numeric results. If more rewrite rules are discovered, DJoin could be extended to support additional operators.

The **design** is based on the following assumptions:

1. All queries know the schema and a rough upper
bound on the total size of each curator’s database- necessary to make BN-PSI-CA and query planning work. 
2. The curators are “honest but curious”, i.e., they will learn whatever information they can, but they will not deviate from the protocol - not inherent (PSI-CA can work in an adversarial model) but helps with efficiency and does not seem unreasonable in practice.
3. Each curator has a “privacy budget” that represents
to amount of private information he or she is willing to release through queries - common for differentially private query processors 
4. The curators can authenticate each querier - can be satisfied, e.g., using cryptographic signatures.

**Overview and roadmap:**
DJoin comprises servers running on curators' machines and a client on the querier's machine. The client communicates with servers to execute queries. Each server has a privacy budget and a local database with a known schema, known to all clients and servers.
Users can issue a query and desired accuracy level to the DJoin client. The client rewrites the query if possible and submits it to the servers. Each server calculates the sensitivity of the query in its local database and, with the desired accuracy level, determines the privacy cost it will incur for answering the query. The final result is obtained through local queries, BN-PSI-CA, and DCR.
The DJoin client uses a distributed commit protocol to identify the query and ensure all servers agree on which query is being executed. 
After the query is committed, the servers execute it in three stages:

- Completion of subqueries with only the local database.
- Joint completion of BN-PSI-CA operations.
- Execution of DCR to combine and add noise to the results.
- The final result is then returned to the client.

**Prototype Implementation:**
The DJoin prototype has been implemented in Java for the runtime engine, in a custom language for FairplayMP for the DCR primitive, and in C++ for the query planner. The prototype includes an implementation of two-party BN-PSI-CA based on the Paillier cryptosystem and optimized for high performance, as well as a query planner that implements the rewrite rules from Section 5.2. The total code for the prototype consists of 3,560 lines of Java, 249 lines of code in FairplayMP's custom language, and 6,776 lines of C++.
Our experiments consisted of a range of different aggregate queries, including
count, sum, average, and maximum. In all cases, the results were noisy using the Laplace mechanism with a privacy budget of ε = 1, and the final result was reported with an accuracy of ν = 10−4 .

**Conclusion:**
In conclusion, DJoin is a privacy-preserving system for executing SQL queries over multiple databases. It combines secure multi-party computation and differential privacy to ensure that the queries do not compromise the privacy of the data. The system has been implemented and evaluated using synthetic data, and although completion times are slower than traditional DBMSs, they are acceptable for occasional analysis tasks or research studies.
The system makes use of two new primitives, BN-PSI-CA and DCR, and operates by rewriting queries into operations on multisets. The authors have implemented a prototype of DJoin and have conducted experiments using synthetic data. Although completion times are higher than traditional DBMS, the system is meant for occasional analysis tasks and research studies, where a few hours of completion time is acceptable.

**Comment by duttabhishek0** [comment]
@tapaswenipathak
