### ISSUE TITLE
Summary : Persistent Personal Names for Globally Connected Mobile Devices

### ISSUE THREAD

**Issue by shashank9aug** [tapaswenipathak/linux-kernel-stats#117]
https://www.usenix.org/legacy/event/osdi06/tech/full_papers/ford/ford.pdf

**Comment by chiragsuthar** [comment]
https://github.com/chiragsuthar

**Comment by chiragsuthar** [comment]
**SUMMARY**

> UIA (Unmanaged Internet Architecture) simplifies global devices connectivity through persistent personal names.

### Based on three key usability concepts:

```
1. Local Introduction, Remote Access.
2. Merging Devices to form Personal Groups.
3. Linking Groups via Personal User Names.
```

### MyNet: a Platform for Secure P2P Personal and Social Networking Services:

> Developed by : **Nokia and Massachusetts Institute of Technology**

- D. N. Kalofonos, 
- Z. Antoniou, 
- F. D. Reynolds, 
- M. Van- Kleek, 
- J. Strauss, 
- P. Wisner

### MyNet:

> **MyNet: platform for secure P2P personal and social networking services**

```
- Built on top of UIA that provides
- Ubiquitous connectivity with network overlays
- Device group management enables non-expert users to easily organize and share their resources within their social neighborhood
- Problem: today managing pervasive access to personal devices, content, and services is too complex for non-expert users

```
### Built on Top of UIA

> **UIA communication platform**

```
- Permanent location independent device identifiers bound to personal names
- Ubiquitous connectivity
- Distributed device group management
```

> **Devices and users**

```
- Device can be uniquely identified by its EID (Endpoint Identifier)
- Devices with multiple-user accounts have a unique EID to identify each device/user pair
- Users (and groups) are identified as a set of EIDS
```

> **Imprinting**

```
- New device becomes a MyNet device though the process of Imprinting the owner's identity, profile, and secret (e.g. PIN)
- Owner "secret" (key) protects against misuse of critical tasks
```

> **Personal Device Clusters (PDC) = personal group**

```
- Imprinted device can be merged with other devices
- Use UIA style "introduction process"
- Discovery via Near Field Communication (NFC) or Bonjour
```

> **Social Contacts**
' -  Adding friends can be done similarly (as in PDC)`

### Basic Design Concepts

> **Services and Content**

```
- Each device can run one or more user-services (a user perceived service)
- Each user-service may be one or more distributed elementary services
```

> **Groups**

```
- User can create a group of users or devices
- Access control privileges can be included
- Built-in user groups: "world", "my direct contacts", and "my extended contacts"
```

### System Components

> **MyNet-"aware" services:**

`- Use MyARPC, a remote procedure call (RPC)`

> **Persistent messaging:**

` - One-way message delivery (even with disruption)`

> **PDC-wide storage**

```
- Share state across multiple devices (for resource sharing)
- RDR (Resource Discovery Record) defines user, device, content, service, passlet
```

> **Secure P2P resource discovery**

```
- RDRS are stored/replicated in the PDC-wide storage
- SRD-client sends a MYARPC request to remote SRD-servers
```

> **User-level access control (via passlets)**

```
- Passlet has info about who is giving permission, to whom, for what, and for how long
- Device passlets vs. Service passlets (PRC calls)
- Passlets are stored in sent and received passiet repositories (in the PDC-store) and are replicated across the PDC
```

**Comment by KavitaMeena23** [comment]
@chiragsuthar pls include section 6, 7 and 8 in the summary

**Comment by duttabhishek0** [comment]
Hi @chiragsuthar, please make the changes if not done.

**Comment by chiragsuthar** [comment]
Hi @duttabhishek0  already done
