### ISSUE TITLE
Summarize : Deterministic Process Groups in dOS

### ISSUE THREAD

**Issue by mahika077** [tapaswenipathak/linux-kernel-stats#126]
https://www.usenix.org/legacy/events/osdi10/tech/full_papers/Bergan.pdf

**Comment by mahika077** [comment]
Problem Statement:
Current multiprocessor systems execute parallel and concurrent software Non deterministically: even when given precisely the same input, two executions of the same program may produce different output. This severely complicates debugging, testing, and automatic replication for fault-tolerance. So, to get over this situation the following suggestions were made in the concerned research paper: (i) to provide fully deterministic execution of arbitrary, unmodified, multithreaded programs as an OS service; and (ii)to make all sources of intentional nondeterminism, such as network I/O, be explicit and controllable. 
The goals are to completely eliminate nondeterminism where possible, including channels beyond shared memory like pipes, signals, and the filesystem, and to make all intentional, external nondeterminism explicit and controllable. To this end, we propose a new OS abstraction, the Deterministic Process Group (DPG).
A DPG is effectively a high-level deterministic virtual machine. The deterministic guarantees are provided transparently by the OS without intervention from the programmer; thus, DPGs can host arbitrary, unmodified application binaries. At any given time, there may be many DPGs running alongside many conventional nondeterministic processes, Record and replay is a natural way to cope with internal nondeterminism during debugging.

Proposed Solution:
We can overcome the above-mentioned problem using Deterministic Process Group (DPG). The  OS supports the deterministic execution of arbitrary programs. It attacks all the sources of nondeterminism (not just shared memory) including multiprocessors. A new DPG is created with the sys marketed system call, and initially hosts just the calling thread. Each new thread spawned by the initial thread is added to the DPG, and in this way the DPG expands to include all descendant threads and processes. Every DPG is monitored by a user-space service called a shim program, also referred to as a shim. Shim programs use the shim layer interface (Figure 3) to observe and control nondeterministic input, Shims use shim trace to wait for a DPG to encounter nondeterminism. shim trace blocks until either (a) a deterministic thread is about to perform a nondeterministic system call, or (b) an external signal is about to be delivered to a deterministic thread.
Prior work on shared-memory determinism has proposed a family of deterministic execution algorithms, including DMPO, DMP-B, and DMP-TM. 

Implementation:
dOS implements the DMP-O ownership-tracking algorithm. Variant of Linux that implements the DPG abstraction.
The dOS scheduler is implemented as a filter in front of the default Linux scheduler—it does not push a deterministic thread into the Linux scheduler until the thread has been scheduled to run by its DPG. This filter implements the DMP-O scheduling algorithm.

Related work:
Kendo proposes a software-only library that provides a set of deterministic synchronization operations that offer some deterministic guarantees for race-free programs. CoreDet proposed DMP-B and used a compiler and runtime system to provide determinism for arbitrary C/C++ programs. Grace [7] uses speculative execution to provide determinism for fork-join parallel programs. Determinator [3] proposes to enforce determinism using a custom microkernel. Like dOS, Determinator supports multiple processes and uses page protection to enforce determinism of shared-memory accesses. Two recent and notable record/replay systems are SMP-ReVirt  and Scribe. Both systems use page ownership similarly to dOS but record ownership transitions rather than imposing a single deterministic order, as in dOS.

Logic:
The choice of deterministic execution algorithm is another factor. Algorithms like DMP-O that provide a strict memory model or make heavy use of barriers will likely perform worse than those that loosen the memory model or rely on alternative mechanisms such as speculation. dOS could have implemented the DMP-TM and DMP-B algorithms we developed in earlier work . Both algorithms have better demonstrated scalability than DMP-O and can both be implemented at the kernel level.

Result:
We introduced the DPG abstraction, which allows programmers to define a deterministic box inside which all communication happens deterministically. We described the shim layer, an interface through which external nondeterminism can be observed and controlled by user space programs. We developed dOS, an implementation of DPGs in Linux. We demonstrated the shim layer with three applications: record/replay, multithreaded replication, and deterministic filesystem services. Our evaluation showed that DPGs have reasonable cost in reactive applications such as Apache and Chromium, and also in several parallel workloads.

**Comment by KavitaMeena23** [comment]
include:
section 4, 5 & 6

**Comment by mahika077** [comment]
> **include the following in the summary**: section 4, 5 & 6

I have already included them, but I will elaborate.

**Comment by duttabhishek0** [comment]
Hi @mahika077 , is the summary updated as per the comment?

**Comment by duttabhishek0** [comment]
@tapaswenipathak closing this one.
