### ISSUE TITLE
Enable CI/CD for the repository 

### ISSUE THREAD

**Issue by chiragsuthar** [tapaswenipathak/linux-kernel-stats#128]
Make sure all files run.

**Comment by chiragsuthar** [comment]
https://github.com/chiragsuthar/linux_kernal_state/actions/runs/4077832983/workflow

**Comment by chiragsuthar** [comment]
https://github.com/chiragsuthar/linux_kernal_state/actions/runs/4091990086/jobs/7056425348

**Comment by chiragsuthar** [comment]
@tapaswenipathak,

In my local system make command is working fine but when i applied it into CI/CD operations it's give some dependencies error which is cloned repos and I haven't idea to how to resolve in .yaml file with make configuration.

![ci-cd-depency](https://user-images.githubusercontent.com/47880785/216821307-ee58c3d6-ac28-4a03-9feb-ea446648c222.png)

**Comment by Madhupatel08** [comment]
hi,
Did you make sure, it is the same file you are running locally? In the current makefile dependencies are commented, Please make changes in the makefile accordingly and then try again.

**Comment by duttabhishek0** [comment]
Hi @chiragsuthar , is the issue resolved?

**Comment by chiragsuthar** [comment]
Yes

**Comment by duttabhishek0** [comment]
@tapaswenipathak
