### ISSUE TITLE
Summary : Dapper, a Large-Scale Distributed Systems Tracing Infrastructure

### ISSUE THREAD

**Issue by Madhupatel08** [tapaswenipathak/linux-kernel-stats#130]
https://storage.googleapis.com/pub-tools-public-publication-data/pdf/36356.pdf

**Comment by Madhupatel08** [comment]
https://www.dropbox.com/scl/fi/plbaaruo3q4qr8jkc77ti/Rough_Test.paper?dl=0&rlkey=gtta6lzc3hzfsmv98p1uw105f 
Summary

**Comment by duttabhishek0** [comment]
@tapaswenipathak closing this one.
