### ISSUE TITLE
Error while running get_release_notes.sh

### ISSUE THREAD

**Issue by KavitaMeena23** [tapaswenipathak/linux-kernel-stats#141]
![Screenshot from 2023-02-04 20-11-10](https://user-images.githubusercontent.com/72209620/216773522-3301c696-eee6-47f5-9e1b-ce7c153f5d86.png)

**Comment by KavitaMeena23** [comment]
@PankajGoswami11

**Comment by tapaswenipathak** [comment]
<img width="1403" alt="Screenshot 2023-02-04 at 8 15 01 PM" src="https://user-images.githubusercontent.com/4143778/216773621-70d36c33-f53d-465f-8cec-dfa2e0951162.png">

cc @chiragsuthar
