### ISSUE TITLE
Not able to extract grep's gitlogs for v2.0

### ISSUE THREAD

**Issue by reddheeraj** [tapaswenipathak/linux-kernel-stats#176]
Issue regarding extraction of gitlogs of v2.0 in (#8 )

**Comment by Madhupatel08** [comment]
![image](https://user-images.githubusercontent.com/54492585/221209422-beafdabd-e56a-4543-9577-6b06a0e38df5.png)

Resolved

**Comment by Madhupatel08** [comment]
@KavitaMeena23 is the kbd repository giving the correct logs for version 2.0?

**Comment by duttabhishek0** [comment]
@tapaswenipathak Can we close this one?

**Comment by duttabhishek0** [comment]
Closing this one(ref commit: 8f2292816ad648195e27a9a498a609a03a95fa29)
