### ISSUE TITLE
CI- CD Errors

### ISSUE THREAD

**Issue by chiragsuthar** [tapaswenipathak/linux-kernel-stats#178]
![CI-CD ISsue2](https://user-images.githubusercontent.com/47880785/221209306-d6f61484-62ea-4cdc-95fd-d4d5e68d5d51.png)

**Comment by chiragsuthar** [comment]
CC: @Madhupatel08

**Comment by chiragsuthar** [comment]
![CI-CD issue4](https://user-images.githubusercontent.com/47880785/221211068-d19c07ad-8fff-4800-9ca2-cdbe62d3211f.png)
cc : @KavitaMeena23

**Comment by reddheeraj** [comment]
<img width="380" alt="image" src="https://user-images.githubusercontent.com/77443480/223480409-fdaab928-1522-4b86-9ef8-3a2838963c72.png">
stable_lines.sh fixed

**Comment by reddheeraj** [comment]
fixed no_of_directories_drivers.sh

**Comment by duttabhishek0** [comment]
Is this issue resolved?

**Comment by reddheeraj** [comment]
> Is this issue resolved?

yes, for the files which were mentioned in this issue.

**Comment by duttabhishek0** [comment]
@tapaswenipathak
