### ISSUE TITLE
For every error we get in log while running the scripts, convert that error message into an valid echo message

### ISSUE THREAD

**Issue by Madhupatel08** [tapaswenipathak/linux-kernel-stats#179]
![image](https://user-images.githubusercontent.com/54492585/221211372-ebfe2cab-e7d8-495a-8079-76498a48ba6c.png)

**Comment by Madhupatel08** [comment]
https://github.com/tapaswenipathak/linux-kernel-stats/issues/178#issuecomment-1443808870

**Comment by duttabhishek0** [comment]
Related issue #178
