### ISSUE TITLE
Unable to grep "spinlock" from git log of v2.0

### ISSUE THREAD

**Issue by KavitaMeena23** [tapaswenipathak/linux-kernel-stats#191]
v2.0 contains spinlock, but due to the unofficial source of v2.0 not able to grep info (https://git.kernel.org/pub/scm/linux/kernel/git/legion/kbd.git/refs/tags)
#187 #186

**Comment by duttabhishek0** [comment]
Closing this one(ref commit: 8f2292816ad648195e27a9a498a609a03a95fa29)
