### ISSUE TITLE
Refer Galvin for Resource Manipulation

### ISSUE THREAD

**Issue by KavitaMeena23** [tapaswenipathak/linux-kernel-stats#195]
![image](https://user-images.githubusercontent.com/72209620/222907038-d6bd8ef4-6411-4d6c-8064-abf465b1e0ca.png)

**Comment by duttabhishek0** [comment]
Related PR: https://github.com/tapaswenipathak/linux-kernel-stats/pull/198/files
@tapaswenipathak
