### ISSUE TITLE
Describe each files' input, logic and ideal output as per the categories decided

### ISSUE THREAD

**Issue by reddheeraj** [tapaswenipathak/linux-kernel-stats#207]

**Comment by reddheeraj** [comment]
https://docs.google.com/document/d/17rMbi2hrSAq2BbTfyDuk5ECE_VEa5jDsoSK4PlGIgls/edit?usp=sharing

**Comment by duttabhishek0** [comment]
@reddheeraj Is it completed?

**Comment by reddheeraj** [comment]
> @reddheeraj Is it completed?

yes. can be closed after a few hours.

**Comment by duttabhishek0** [comment]
@tapaswenipathak
