### ISSUE TITLE
Error in Extended scripts for different versions

### ISSUE THREAD

**Issue by reddheeraj** [tapaswenipathak/linux-kernel-stats#215]
![image](https://user-images.githubusercontent.com/77443480/229285234-88b4fd73-c284-48e3-ac41-bf2b0e5153f9.png)

if this is written in code:
<img width="351" alt="image" src="https://user-images.githubusercontent.com/77443480/229285302-9abf5925-8709-455b-96a6-f6feb62eda8c.png">
then it will not exactly add the version to array:
<img width="274" alt="image" src="https://user-images.githubusercontent.com/77443480/229285321-e2d59645-380a-4327-b427-393911c823d4.png">

solution:
<img width="335" alt="image" src="https://user-images.githubusercontent.com/77443480/229285265-4d21f1bd-f3ba-4769-b5c7-4e11f9e10283.png">

@duttabhishek0

**Comment by duttabhishek0** [comment]
@reddheeraj can you post the code in text?

**Comment by reddheeraj** [comment]
> @reddheeraj can you post the code in text?

need to change this: all_versions+=${ver_name}
to this: all_versions+=("$ver_name")
