### ISSUE TITLE
error while running list_of_drivers.sh 

### ISSUE THREAD

**Issue by PankajGoswami11** [tapaswenipathak/linux-kernel-stats#241]
![image](https://user-images.githubusercontent.com/123570407/231256295-a54a1cfc-8a4c-4b6d-9cbe-53504c015a41.png)

**Comment by duttabhishek0** [comment]
@PankajGoswami11 Can you check if there is `driver`  sub-directory under `linux-stable/linux-stabl` ?

**Comment by PankajGoswami11** [comment]
Yes it's there
