### ISSUE TITLE
Get all release notes from first release till latest rc

### ISSUE THREAD

**Issue by KavitaMeena23** [tapaswenipathak/linux-kernel-stats#45]
Initial work: (https://www.dropbox.com/scl/fi/1x0myqjac5ywjrfyoewhl/All-Release-Notes.paper?dl=0&rlkey=pe2t86odmttrlp8612ar8ngby)

**Comment by tapaswenipathak** [comment]
https://lkml.org/lkml/2022/10/16/359
https://www.lkml.org/lkml/2019/5/5/278
https://lkml.org/lkml/2019/4/14/265
https://lkml.org/lkml/2019/4/14/265
https://lkml.org/lkml/2019/3/24/487
https://lkml.org/lkml/2019/3/17/207
https://lkml.org/lkml/2019/4/28/270
https://lkml.org/lkml/2019/3/31/256

**Comment by duttabhishek0** [comment]
Completed(related PR: https://github.com/tapaswenipathak/linux-kernel-stats/pull/122) @tapaswenipathak
