### ISSUE TITLE
Update all scripts to include versions < 2.6.11

### ISSUE THREAD

**Issue by KavitaMeena23** [tapaswenipathak/linux-kernel-stats#54]
Not able to update drivers.sh, no_of_directories_drivers.sh, list_of_drivers.sh

Repository links:
https://git.kernel.org/pub/scm/linux/kernel/git/legion/kbd.git/
https://git.kernel.org/pub/scm/linux/kernel/git/xiang/erofs-utils.git/

**Comment by duttabhishek0** [comment]
Closing it, as reference already added in the PR #251
