### ISSUE TITLE
Summary - Digging for data structures

### ISSUE THREAD

**Issue by reddheeraj** [tapaswenipathak/linux-kernel-stats#86]
https://www.usenix.org/legacy/events/osdi08/tech/full_papers/cozzie/cozzie.pdf

**Comment by reddheeraj** [comment]
Anthony Cozzie, Frank Stratton, Hui Xue, and Samuel T. King examine the use of abstractions in creating sophisticated computer systems and the drawbacks of interfaces in their work titled "Digging For Data Structures." It emphasizes how hard-coding the mapping between the interface and the structure built on top of it allows system designers to bridge the gap between levels of abstraction when they need more information. This approach, meanwhile, is fragile and prone to mistakes.
 The paper offers a new method called "Laika" that uses the concept of compound data structures, a little piece of software engineering used to group data into objects, to recognize data structures in a memory representation of a program. It aims to make the process of detecting data structures more efficient. 
Laika, a machine learning technique that finds viruses in memory pictures of active programs, is introduced in this work. Laika works by locating and measuring things in the memory image, then comparing comparable objects based on their byte values. It uses unsupervised learning to classify objects in a program based on their data structures. The algorithm converts objects from sequences of raw bytes into semantically valued blocks and clusters objects with similar sequences of blocks together using Bayesian unsupervised learning. The technique avoids code polymorphism found in contemporary worms by categorizing programs based on their data structures. By creating a virus checker on top of Laika that is over 99% accurate, as opposed to 85% for a top open-source virus detector, the authors show the value of Laika.
The algorithm scans through the image looking for pointers and uses them to estimate the positions of objects. It estimates the sizes of objects during clustering and classifies objects with fixed sizes. The authors suggest that details of malloc library might improve Laika's accuracy, but this approach is difficult due to the variety of malloc implementations and address space locality. The article also mentions that Laika's classification accuracy is reasonable but not perfect, particularly on larger programs. The article also describes how data objects and variance in size can cause errors in Laika's classification, and how removing random data, freed chunks, and malloc information improve Laika's results.
The authors of this work suggest a novel method of classifying computer viruses according to their data structures. Laika counts how frequently items from various photos are assigned to the same category and runs on the memory images of two programs simultaneously. The two programs are similar if numerous classes contain objects from both. Laika can discover patterns in images together and is more accurate when given more samples of a class. The mixture ratio detects changes to the frequency with which the data structures are used, which is important for detecting viruses. This method helps Laika detect viruses quite accurately even when it does not correctly identify all of their data structures.
The authors tested their approach on three different botnets: Agobot/Gaobot, Storm, and Kraken. They ran the bots in QEMU to defeat their VM detection and took snapshots of their memory images using WinDbg, using a simple maximum likelihood classifier, with the single parameter being the mixture ratio between the unknown program and a sample of the virus. The detector takes from 3 seconds for small applications and up to 20 minutes for large applications. They found that the detector could detect the viruses with high accuracy.

**Comment by KavitaMeena23** [comment]
**mention the following in your summary:**
1. describe section 2
2. brief section 5.1, 5.2, 5.3
3. related work (section 6)

**Comment by KavitaMeena23** [comment]
**Reviewed**

**Comment by duttabhishek0** [comment]
@tapaswenipathak
