### ISSUE TITLE
Summarize: Deconstructing RDMA-enabled Distributed  Transactions: Hybrid is Better!

### ISSUE THREAD

**Issue by pratik2315** [tapaswenipathak/linux-kernel-stats#88]
https://www.usenix.org/system/files/osdi18-wei.pdf

**Comment by pratik2315** [comment]
**Deconstructing RDMA-enabled Distributed Transactions: Hybrid is Better**

The following paper is based upon the ongoing argument that debates which RDMA primitive (i.e., one sided or two sided) is optimal for distributed transactions. RDMA (Remote Direct Memory Access) is a network feature with high speed, low latency, and low CPU overhead. Although distributed transactions used to seem slow, the introduction of fast networking features such as RDMA has significantly boosted the performance of distributed transactions. According to a number of experiments, each RDMA primitive was shown with better performance than the other under different circumstances. In the paper, authors Xingda Wei, Zhiyuan Dong, Rong Chen, and Haibo Chen of Shanghai Jiao Tong University discuss how we can use different RDMA primitives at each phase of transactions. Hence, they propose a hybrid solution, since no single primitive is able to outweigh the cons of its rival primitive. The paper compares how previous systems leveraged RDMA by evaluating three representative designs upon a single execution framework. As mentioned, The experiment results show that none of the primitives has the optimal performance. 

Based on the above studies, the authors build DrTM+H, a new hybrid distributed transaction system that always embraces the optimal RDMA primitives at each phase of transactional execution. The hybrid design proposed by the authors is able to outperform the pure two-sided design (FaSST) and the pure one-sided design (DrTM+R) by up to 2.96X and 1.89X for simplified TPC-C, respectively. 

In the phase-by-phase analysis of different RDMA primitives, it was found that, If one round-trip RDMA READ can retrieve one record using the index cache, one-sided primitive is always a better choice than a two-sided one. But if servers are not overloaded, two-sided primitive should be used as it proved to be a better alternative. Hence by utilizing both primitives, a hybrid scheme was used in the execution phase by the authors. By showing how to improve the performance of prior designs by choosing appropriate primitives and techniques at different phases of transactional execution, the authors were able to produce DrTM+H, an efficient distributed transaction system using hybrid schemes. Compared to other prior designs demonstrated in the paper, DrTM+H always embraces the best performance in terms of latency and throughput. DrTM+H has the best throughput than previous designs with the right choice of RDMA primitives and a set of optimizations to better leverage the chosen primitive. 

The paper emphasizes why it is very important to properly choose the right primitive given a specific workload. Unlike previous studies, authors have compared different primitives and techniques using one well-optimized RDMA framework. This makes the comparison of techniques and primitives comparable and comprehensive. This paper gives an example of how to optimize transactional processing with a combination of different primitives in a phase-by-phase way. The paper also gives hints about whether it is cost-effective to offload RDMA one-sided, or just use two-sided for easy porting. The resulting system and insights proposed in the paper may be reused for further studies.

**Comment by KavitaMeena23** [comment]
**mention the following in the summary:**
1. brief about the background (section 2)
2. include section 4
3. brief about evaluation (section 5 & subsections)
4. explain section 6

**Comment by duttabhishek0** [comment]
Hi @pratik2315 , are the changes done?

**Comment by duttabhishek0** [comment]
@tapaswenipathak closing it!
