### ISSUE TITLE
Generate loc-rc.png output file showing lines of code evolution of all rc versions

### ISSUE THREAD

**Issue by KavitaMeena23** [tapaswenipathak/linux-kernel-stats#9]
- [ ]  lines of code in all rc versions

**Comment by KavitaMeena23** [comment]
# Output of loc.sh
v2.6.12
6215530
v2.6.13
6405586
v2.6.14
6561973
v2.6.15
6684260
v2.6.16
6850888
v2.6.17
6951625
v2.6.18
7082952
v2.6.19
7290279
v2.6.20
7400843
v2.6.21
7522286
v2.6.22
7744727
v2.6.23
7818168
v2.6.24
8082358
v2.6.25
8396250
v2.6.26
8535933
v2.6.27
8690888
v2.6.28
9128690
v2.6.29
9871260
v2.6.30
10419567
v2.6.31
10778469
v2.6.32
11242136
v2.6.33
11564768
v2.6.34
11861616
v2.6.35
12250679
v2.6.36
12539782
v2.6.37
13006967
v2.6.38
13289311
v2.6.39
13600071
v3.0
13688408
v3.1
13804451
v3.2
14017008
v3.3
14173668
v3.4
14370856
v3.5
14556354
v3.6
14811965
v3.7
15108939
v3.8
15310436
v3.9
15563152
v3.10
15803499
v3.11
16225814
v3.12
16529850
v3.13
16703764
v3.14
17002462
v3.15
17321190
v3.16
17525235
v3.17
17481114
v3.18
17582782
v3.19
17688727
v4.0
17844517
v4.1
18001559
v4.2
18752858
v4.3
19028169
v4.4
19240140
v4.5
19486038
v4.6
19720726
v4.7
19968006
v4.8
20262447
v4.9
20516733
v4.10
20860090
v4.11
21127569
v4.12
22120551
v4.13
22693739
v4.14
23045997
v4.15
23324938
v4.16
23491129
v4.17
23309859
v4.18
23178729
v4.19
23444031
v4.20
23771378
v5.0
23927800
v5.1
24135777
v5.2
24170101
v5.3
24703431
v5.4
25054010
v5.5
25307810
v5.6
25562895
v5.7
25789096
v5.8
26280595
v5.9
26690848
v5.10
26920230
v5.11
27465244
v5.12
27631012
v5.13
27960690
v5.14
28453135
v5.15
28720846
v5.16
29072947
v5.17
29260833
v5.18
29926924
v5.19
30646046
v6.0
31519628

**Comment by duttabhishek0** [comment]
@tapaswenipathak
