### ISSUE TITLE
Verification of extension.sh

### ISSUE THREAD

**Issue by PankajGoswami11** [tapaswenipathak/linux-kernel-stats#94]

**Comment by PankajGoswami11** [comment]
```
v0.11
     51 c 	  verified
     33 h	  verified
      7 s	  verified
      2 txt	   no
      1 sh	   no
      1 S	   verified 
      1 git	    no 




v0.96-pre
     70 c	verified 
     50 h	verified 
      4 S	verified 
      3 s	verified 
      2 txt	   no
      2 sh	    1
      1 git	   no
```

**Comment by PankajGoswami11** [comment]
### verified 
![Screenshot from 2023-04-20 14-22-56](https://user-images.githubusercontent.com/123570407/233318638-57a93918-e992-4327-93b3-8463a31abed4.png)

![image](https://user-images.githubusercontent.com/123570407/233314409-e13cf783-9b97-40cf-85ed-e0b18673f4af.png)

**Comment by duttabhishek0** [comment]
@tapaswenipathak closing as verification complete.
