### ISSUE TITLE
Summary - Stable Deterministic Multithreading through Schedule Memoization 

### ISSUE THREAD

**Issue by reddheeraj** [tapaswenipathak/linux-kernel-stats#98]
https://www.usenix.org/legacy/events/osdi10/tech/full_papers/Cui.pdf

**Comment by reddheeraj** [comment]
**Stable Deterministic Multithreading through Schedule Memoization**

**Abstract**
The authors present **TERN**, a deterministic multithreading (DMT) system that eliminates nondeterminism in thread scheduling. The system is unique as it features schedule memoization and windowing which enables stability across different inputs, making it suitable for server programs with continuous and nondeterministic inputs. TERN operates as a user-space scheduler and has been evaluated on a diverse set of 14 programs with real and synthetic workloads. Results show that TERN is easy to use, improves program determinism and stability, and has reasonable overhead.

**Introduction**
The authors discuss the challenges of writing, testing, and debugging multithreaded programs. The main issue is the nondeterminism of different runs of a multithreaded program, which can show different behaviours based on the interleaving of threads. This nondeterminism is caused by two factors: scheduling and input. The first factor, scheduling, refers to the way the OS and hardware schedule threads. The second factor, input, refers to the data that arrives and its timing. While some input nondeterminism is essential, frequently it is not, and the same schedule can be used for many different inputs.

Deterministic multithreading (DMT) systems aim to make threads more deterministic by eliminating scheduling nondeterminism, but they do not reduce input nondeterminism. As a result, they may create the instability problem where a slight change to inputs may force a program into a vastly different and potentially buggy schedule. This can make it difficult to reproduce bugs and make testing more challenging. Existing DMT systems may also be affected by minor changes in the execution environment, further contributing to the instability problem.

The paper presents **TERN**, **a schedule-centric, stateful dynamic multi-threading (DMT) system.** TERN aims to address the instability problem commonly faced by DMT systems by using a technique called "schedule memoization." This technique involves memorizing past working schedules and reusing them for future inputs, rather than generating new schedules each time an input is received. This avoids potential errors in unknown schedules and also reduces the overhead of schedule generation.
To handle the challenges posed by server programs that frequently use threads, TERN uses a technique called "windowing." This involves splitting the continuous request stream of a server into windows, allowing the server to quiesce in between windows, and then memoizing and reusing schedules across windows. Within a window, TERN only admits requests at fixed schedule points, reducing timing nondeterminism.
The authors have implemented TERN in Linux and evaluated it on a diverse set of 14 programs, including Apache and MySQL server programs. The results show that TERN is easy to use, enforces stability, has reasonable overhead, and makes threads deterministic. The authors believe that TERN is the first stable DMT system and has the potential to be deployed today.

**Background**
The authors discuss the background information on TERN, a Deterministic Multi-Threading (DMT) system. The main focus is on the instability problem of existing DMT systems, the choice of schedule representation in TERN, and why TERN can reuse schedules across inputs. Existing DMT systems have a problem with instability, meaning that similar inputs often map to different schedules. 
TERN represents schedules as **synchronization orders for efficiency**, as they can be reused more frequently than memory access orders. Additionally, researchers have found that many concurrency errors can be deterministically reproduced or avoided using synchronization orders.
An argument is made for the **frequent reuse of schedules** in TERN by presenting both an intuitive argument and empirical evidence. Intuitively, synchronization operations map to developer intents for inter-thread control flow and by enforcing the same synchronization order, the same inter-thread path is fixed while still allowing different inputs to flow down this path. Empirical evidence was obtained by studying the input constraints for five programs, and the results showed that the input constraints were often general, allowing frequent reuses of schedules.

**Architecture**
TERN operates in user-space on commodity hardware, and its design is guided by several goals: backward compatibility, stability, efficiency, and best-effort determinism. The system is comprised of five components: instrumentor, schedule cache, proxy, replayer, and memoizer. To use TERN, developers annotate their application with information on which input data may affect synchronization operations. The program is then compiled with the instrumentor, which intercepts synchronization operations so that TERN can control them at runtime. The schedule cache stores memoized schedules and their input constraints, which can be reused if the input conditions are met. 
The proxy queries the schedule cache for a matching constraint-schedule tuple, and on a cache hit, it lets the replayer enforce the schedule. On a cache miss, the memoizer runs the program to memoize a new schedule by recording all synchronization operations and computing input constraints via symbolic execution. The memoizer can check for data races and discard a memoized schedule if needed. 
There are three deployment scenarios for TERN, where each scenario has its own pros and cons, and the recommended deployment modes depend on the performance requirements of the program. 

**Interface**
TERN has an annotation interface that allows developers and instrumentors to mark up multithreaded programs. The annotations fall into four categories: (1) symbolic annotations for data that affects schedules, (2) task boundary annotations to mark the beginning and end of logical tasks, (3) wrappers for synchronization operations, and (4) hooks around blocking system calls. These annotations enable TERN to function as a parasitic user-space scheduler that oversees the scheduling decisions of the OS and synchronization library.

**Schedule Memoization****
The idea of schedule memoization for batch programs is presented by the authors. TERN memoizes schedules by logging and controlling synchronization operations using a round-robin algorithm by default. TERN can also use a first-come first-served algorithm if the round-robin detects a race. The memoizer tracks input constraints by logging the outcomes of branch statements and the data derived from symbolic data marked by developers. The constraints are collected using KLEE, a symbolic execution engine adapted to TERN by modifying it to support threads and to only collect constraints. TERN stores the memoized schedules and constraints in a decision tree in the schedule cache.

**Windowing**
TERN addresses the challenges of timing non-determinism and specific schedules in server programs by using a technique called "**windowing**", which allows TERN to handle the evolution of server states and make accurate schedule selections. The idea behind windowing is to break a continuous stream of client requests into windows and process requests only at fixed points in the current schedule. Requests that arrive during a window are buffered so they do not interfere with the running window. TERN memoizes and reuses schedules across windows, which reduces concurrency and may impact server throughput, but experiments have shown that the cost is reasonable. 

**Refinements**
This paper describes **refinements made to TERN**, a tool for deterministically reusing schedules of multi-threaded programs. Four refinements are described: (1) **detecting data races**, (2) **skipping unnecessary synchronizations**, (3) **simplifying constraints**, and (4) **slicing out irrelevant branches**. These refinements ensure that the schedules can be deterministically reused and make the process faster. The race detector checks if a schedule allows for data races and flags any that are found. Skipping unnecessary synchronizations saves time. Simplifying constraints makes constraint checking more efficient, and slicing out irrelevant branches reduces constraint checking time.

**Evaluation**
TERN consists of 8,934 lines of C++ code, including components for instrumentation, a proxy, a schedule cache, a memoizer, and a replayer. The authors evaluated TERN on a diverse set of 14 programs.
The authors focused their evaluation on four key questions: (1) ease of use, (2) stability across different inputs, (3) overhead, and (4) determinism on the same input. The results show that TERN is easy to use and requires only a few modifications to the programs. The stability of TERN was evaluated in two sets of experiments: (1) a comparison to an existing DMT system (COREDET) in terms of bug stability and (2) the frequency of schedule reuse on real and synthetic workloads. The results showed that TERN was more stable than COREDET and had a high schedule reuse rate. In terms of overhead, TERN incurred a moderate overhead, but it was able to reduce the overhead by reusing schedules. Finally, the results showed that TERN made the programs deterministic on the same input.
In conclusion, the authors believe that TERN is a practical and effective solution for making multithreaded programs deterministic and stable.

**Related Work**
TERN is a deterministic multi-threaded (DMT) system that makes threads stable and reduces timing non-determinism. It is different from existing DMT systems such as Kendo and COREDET, which are software-only systems that enforce synchronization and memory access orders, respectively. TERN is also different from deterministic replay systems such as Scribe, Capo, PRES, ODR, and SMP-ReVirt, which aim to replay recorded executions. TERN is complementary to existing work on concurrency errors and provides value even for programs without errors by making their behaviors repeatable. TERN applies symbolic execution to a new domain by tracking input constraints to reuse schedules.

To conclude, the authors present **TERN**, a deterministic multi-threading system that makes general multithreaded programs stable by repeating the same schedules on different inputs. TERN uses schedule memoization to achieve this and has been shown to have reasonable overhead. The authors have evaluated TERN on a diverse set of real programs, and have found that it is easy to use and makes programs more deterministic and stable. TERN is the first DMT system shown to work on large, complex, and nondeterministic applications like MySQL and Apache, demonstrating the potential for DMT to be deployed today.

**Comment by KavitaMeena23** [comment]
@reddheeraj  include limitations (section 3.4)

**Comment by Madhupatel08** [comment]
+1

**Comment by duttabhishek0** [comment]
@tapaswenipathak
