### ISSUE TITLE
Summary - Project Adam: Building an Efficient and Scalable Deep Learning Training System

### ISSUE THREAD

**Issue by reddheeraj** [tapaswenipathak/linux-kernel-stats#99]
https://www.usenix.org/system/files/conference/osdi14/osdi14-paper-chilimbi.pdf

**Comment by reddheeraj** [comment]
PROJECT ADAMS

Large deep neural networks provide excellent accuracy on visual recognition tasks. But it takes a lot of time to train them and they require large amounts of computation cycles. The authors, Trishul Chilimbi, Yutaka Suzue, Johnson Apacible, and Karthik Kalyanaraman present a solution for this problem. They describe the design and implementation of a distributed system called “**Adam**”, which is more **efficient and scalable**. The authors claimed that it provided 2x higher accuracy in comparable time on the ImageNet 22,000 category image classification task than the system that previously held the record for this benchmark. 

The design and implementation of Adam are discussed in this paper. The authors worked on making it **easier to train big neural networks** by making sure the computers and communication between them work well together. The big models were divided into smaller parts and they attempted to use less memory and communication between the machines. 

They developed a process of training large machine learning models more efficiently. They were able to train a big model using fewer machines and it was more accurate than previous methods which also lead to the conclusion that using **bigger models leads to even better results**. This research suggests that it is possible to **improve the accuracy** of deep learning predictions by **training larger models on big datasets** using efficient and scalable computer systems. This approach is different from the traditional approach which focuses mainly on improving the algorithms used in machine learning.

The article explains the technology behind Adam, which is a system for training deep neural networks. It uses a specific setup, called **Multi-Spert**, that involves separate machines for providing data and training the model. The system uses multiple copies of the model, which are all updated at the same time by a central server. This method is called **asynchronous training**. Adam is designed to be efficient, with features like multi-threading, quick weight updates, and memory optimizations. It can be used to train any kind of deep neural network using a common method called back-propagation.

The **parameter server** in Adam is a system that **helps manage the updates** made to a deep neural network during training. It receives updates from the training machines and sends the current values of the model's parameters. It is optimized for speed and reliability, with features such as dividing the parameters into smaller chunks and storing multiple copies for fault tolerance. It also uses high-speed networking to ensure **efficient communication** between the different components of the system.
Adam is a system that is being evaluated using two benchmarks for image recognition tasks called **MNIST** and **ImageNet**. MNIST is a small dataset of 60,000 images used to measure the accuracy of trained models and ImageNet is a large dataset with over 15 million images used to measure the performance and scaling of Adam. 

It was found that Adam was able to **train large models with a small number of machines** and that it **improves efficiency as more machines are added**. It was observed that it is efficient and can train larger models with the same amount of resources. Additionally, they also found that training larger models increased task accuracy and that Adam's efficiency and scalability enabled training larger models.
To conclude, it was shown through this paper that utilizing large-scale commodity distributed systems can efficiently train deep neural networks (DNNs) to achieve world-record accuracy on challenging vision tasks with current training algorithms. By utilizing Adam optimization, the authors were able to train a large DNN model that achieved record-breaking classification performance on the ImageNet 22K category task.

**Comment by KavitaMeena23** [comment]
**Reviewed**

**Comment by duttabhishek0** [comment]
@tapaswenipathak
